Repository bucket-back/bucket-back-frontend, pull requests merged in 2023-10, with the labels that each got.

#3 [OMCT-58] 기술스택 수정
  README.md
Labels: documentation

#4 [OMCT-59] PR 템플릿 추가
  .github/pull_request_template.md
Labels: documentation

#5 [OMCT-60] vite 초기세팅 추가
  .eslintrc.cjs
  .gitignore
  index.html
  package.json
  public/vite.svg
  src/App.tsx
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: enhancement

#6 [OMCT-61] eslint, prettier 세팅 추가
  .eslintrc.cjs
  .prettierrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
Labels: 🐣 Feat

#7 [OMCT-64] 기술 스택에 작성된 라이브러리 설치
  package-lock.json
  package.json
Labels: 🏅 Chore

#8 [OMCT-63] 디렉터리 구조 세팅
  src/apis/index.ts
  src/components/common/index.ts
  src/constants/index.ts
  src/hooks/index.ts
  src/mocks/index.ts
  src/pages/index.ts
  src/routes/index.ts
  src/types/index.ts
Labels: 🐹 init

#9 [OMCT-62] dev 브랜치를 main 브랜치에 병합
  .eslintrc.cjs
  .github/pull_request_template.md
  .gitignore
  .prettierrc.cjs
  README.md
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/apis/index.ts
  src/components/common/index.ts
  src/constants/index.ts
  src/hooks/index.ts
  src/main.tsx
  src/mocks/index.ts
  src/pages/index.ts
  src/routes/index.ts
  src/types/index.ts
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 🐹 init

#10 [OMCT-70] ChakraProvider 추가
  src/main.tsx
Labels: 🐣 Feat

#14 [OMCT-120] 라이브러리 추가
  .commitlintrc.json
  .eslintrc.cjs
  .husky/commit-msg
  .husky/pre-commit
  package-lock.json
  package.json
Labels: 🐹 init

#11 [OMCT-68] commonTabs 컴포넌트 구현
  src/components/common/Tabs/index.tsx
Labels: 🐣 Feat

#12 [OMCT-77] CommonDrawer 컴포넌트 구현
  src/components/common/Drawer/index.tsx
Labels: 🐣 Feat

#13 [Omct 75] 브라우저에 Service worker 등록
  package.json
  src/main.tsx
  src/mocks/browser.js
  src/mocks/handler.ts
Labels: 🐹 init

#15 [OMCT-101] CommonDivider 컴포넌트 구현 및 commitlint 룰 추가
  .commitlintrc.json
  src/components/common/Divider/index.tsx
Labels: 🐣 Feat
