Repository bucket-back/bucket-back-frontend, pull requests merged in 2023-12, with the labels that each got.

#190 [OMCT-393] 버킷 생성시 아이템 목록 무한 스크롤 구현
  src/App.tsx
  src/features/bucket/components/BucketSelectItem/index.tsx
  src/features/bucket/components/BucketSelectItem/style.ts
  src/features/comment/hooks/useAddComment.ts
  src/features/feed/components/FeedSelectBucket/style.tsx
  src/features/item/service/queryOption.ts
  src/pages/Bucket/BucketCreate/index.tsx
  src/pages/Bucket/BucketCreate/style.ts
  src/pages/Feed/FeedDetail/index.tsx
Labels: 🐣 Feat, 🔨 Fix

#192 [O MCT-396] 랭킹 페이지 구현
  src/features/rank/components/index.ts
  src/features/rank/components/rankList/index.tsx
  src/features/rank/components/rankList/style.tsx
  src/features/rank/service/handler.ts
  src/features/rank/service/index.ts
  src/features/rank/service/queryOption.ts
  src/features/rank/service/type.ts
  src/pages/Search/SearchMain/index.tsx
  src/pages/Search/SearchMain/style.tsx
Labels: 🐣 Feat

#191 [OMCT-394] QA 반영 및 개인적으로 찾은 오류 수정
  index.html
  src/features/bucket/components/BucketSelectItem/index.tsx
  src/features/bucket/components/BucketSelectItem/style.ts
  src/features/comment/components/CommentItem/index.tsx
  src/features/feed/components/FeedHomeList/index.tsx
  src/features/feed/components/FeedItem/index.tsx
  src/features/feed/components/FeedItem/style.tsx
  src/features/feed/components/FeedMemberList/index.tsx
  src/features/feed/hooks/useDeleteFeed.ts
  src/features/feed/hooks/useUpdateFeed.ts
  src/features/member/components/MemberEditForm/index.tsx
  src/pages/Bucket/BucketDetail/index.tsx
  src/pages/Bucket/BucketDetail/style.ts
  src/pages/Feed/FeedCreate/index.tsx
  src/pages/Feed/FeedDetail/index.tsx
  src/pages/Feed/FeedUpdate/index.tsx
  src/pages/Member/MemberHome/index.tsx
  src/pages/Member/MemberHome/style.tsx
  src/shared/components/Footer/index.tsx
  src/shared/components/Icon/index.tsx
  src/shared/styles/ImageBorder.ts
Labels: 🎨 Design, 🐣 Feat, 🔨 Fix

#193 [OMCT-391] 아이템 리뷰 무한 스크롤 / QA 반영
  src/features/item/components/ItemComment/index.tsx
  src/features/review/hooks/useEditReview.ts
  src/features/review/hooks/usePostReview.ts
  src/features/review/service/queryOption.ts
  src/features/search/components/searchItemList/index.tsx
  src/features/search/service/types.ts
  src/pages/Item/Detail/index.tsx
  src/pages/Item/Detail/style.tsx
  src/pages/Item/List/style.tsx
  src/pages/Item/Review/index.tsx
  src/pages/Item/ReviewEdit/index.tsx
  src/shared/components/Header/index.tsx
Labels: 🔨 Fix, 🛠 Refactor

#195 [OMCT-392] qa반영 + 무한스크롤
  src/features/inventory/components/InventorySelectItem/index.tsx
  src/features/inventory/service/queryOption.ts
  src/features/member/components/MemberNicknameForm/index.tsx
  src/features/vote/components/VoteSelectItem/index.tsx
  src/features/vote/hooks/useCreateVote.ts
  src/pages/Inventory/InventoryCreate/index.tsx
  src/pages/Inventory/InventoryDetail/index.tsx
  src/pages/Member/Login/index.tsx
  src/pages/Member/Signup/index.tsx
  src/shared/components/Image/index.tsx
Labels: 🐣 Feat, 🛠 Refactor

#196 [OMCT-399] 404 페이지 / 2차 QA 반영
  src/assets/images/404_error.png
  src/core/routes/router.tsx
  src/features/item/service/types.ts
  src/features/search/components/searchItemList/index.tsx
  src/features/search/components/searchList/index.tsx
  src/features/search/components/searchVoteList/index.tsx
  src/features/search/service/types.ts
  src/pages/404/index.tsx
  src/pages/404/style.tsx
  src/pages/Item/Detail/index.tsx
  src/pages/Item/List/index.tsx
  src/pages/Item/List/style.tsx
  src/pages/Item/Review/index.tsx
  src/pages/Item/Review/style.tsx
  src/pages/Item/ReviewEdit/index.tsx
  src/pages/Item/ReviewEdit/style.tsx
  src/pages/index.ts
  src/shared/components/Spinner/index.tsx
  src/shared/components/index.ts
  src/shared/utils/formatNumber.ts
Labels: 🔨 Fix, 🛠 Refactor

#197 [OMCT-400] 투표페이지 전체 아이템 갯수 수정
  src/features/vote/components/VoteSelectItem/index.tsx
Labels: 🛠 Refactor

#198 [NO-JIRA] 전체적인 수정
  src/core/routes/router.tsx
  src/features/bucket/components/BucketSelectItem/index.tsx
  src/features/bucket/components/BucketSelectItem/style.ts
  src/features/feed/components/FeedItem/index.tsx
  src/features/feed/components/FeedItem/style.tsx
  src/features/feed/components/FeedItemsDetail/index.tsx
  src/features/feed/components/FeedItemsDetail/style.tsx
  src/features/inventory/components/InventorySelectItem/index.tsx
  src/features/item/components/ItemComment/index.tsx
  src/features/item/components/ItemComment/style.tsx
  src/features/item/components/ListItem/index.tsx
  src/features/item/components/ListItem/style.tsx
  src/features/item/components/index.ts
  src/features/search/components/searchItemList/style.tsx
  src/features/search/components/searchVoteList/index.tsx
  src/features/search/components/searchVoteList/style.tsx
  src/features/vote/components/VoteItem/index.tsx
  src/features/vote/components/VoteItem/style.tsx
  src/features/vote/components/VoteSelectItem/index.tsx
  src/features/vote/components/Votes/style.tsx
  src/pages/Bucket/BucketCreate/index.tsx
  src/pages/Bucket/BucketCreate/style.ts
  src/pages/Bucket/BucketDetail/index.tsx
  src/pages/Bucket/BucketDetail/style.ts
  src/pages/Inventory/InventoryCreate/index.tsx
  src/pages/Inventory/InventoryDetail/index.tsx
  src/pages/Inventory/InventoryDetail/style.ts
  src/pages/Item/Detail/index.tsx
  src/pages/Item/Detail/style.tsx
  src/pages/Item/ReviewEdit/index.tsx
  src/pages/Item/ReviewEdit/style.tsx
  src/pages/Search/SearchHome/style.tsx
  src/pages/Search/SearchResult/style.tsx
  src/shared/components/Button/index.tsx
  src/shared/components/Footer/index.tsx
  src/shared/components/IconButton/index.tsx
  src/shared/components/Image/index.tsx
  src/shared/hooks/useUserInfo.ts
  src/shared/styles/ImageBorder.ts
Labels: 🎨 Design

#204 [NO-JIRA] README 작성
  README.md
Labels: 🐣 Feat

#205 [NO-JIRA] README 내용 수정
  README.md
Labels: 🐣 Feat

#207 [OMCT-404] 안쓰는 폴더 삭제
  src/apis/index.ts
  src/components/common/index.ts
  src/constants/index.ts
  src/features/bucket/index.ts
  src/features/vote/index.ts
  src/hooks/index.ts
  src/mocks/index.ts
  src/routes/index.ts
  src/types/index.ts
Labels: 🛠 Refactor

#208 [OMCT-405] 인벤토리, 투표 생성페이지 중복코드 삭제
  src/pages/Inventory/InventoryCreate/index.tsx
  src/pages/Inventory/InventoryCreate/style.ts
  src/pages/Vote/VoteCreate/index.tsx
  src/pages/Vote/VoteCreate/style.ts
  src/shared/components/CreateTemplate/index.tsx
  src/shared/components/CreateTemplate/style.ts
  src/shared/types/hobby.ts
  src/shared/types/item.ts
Labels: 🛠 Refactor

#209 [NO-JIRA] 쿼리키팩토리 삭제 후 에러바운더리 설치
  package-lock.json
  package.json
Labels: 🏅 Chore

#210 [OMCT-407] 인벤토리 staleTime설정
  src/features/hobby/hooks/useHobby.ts
  src/features/inventory/components/InventorySelectItem/index.tsx
  src/features/inventory/hook/useCreateInventory.tsx
  src/features/inventory/hook/useDeleteInventory.tsx
  src/features/vote/components/VoteSelectItem/index.tsx
  src/pages/Inventory/InventoryDetail/index.tsx
  src/pages/Inventory/InventoryHome/index.tsx
Labels: 🛠 Refactor
