Repository bucket-back/bucket-back-frontend, pull requests merged in 2023-11, with the labels that each got.

#16 [OMCT-103] CommonSlider 컴포넌트 구현
  src/components/common/Slider/index.tsx
Labels: 🐣 Feat

#18 [OMCT-115] CommonBadge 컴포넌트 구현
  src/components/common/Badge/index.tsx
Labels: 🐣 Feat

#22 [OMCT-107] CommonIcon 컴포넌트 구현
  src/components/common/Icon/index.tsx
Labels: 🐣 Feat

#19 [OMCT-110] CommonImage 컴포넌트 구현
  src/components/common/Image/index.tsx
Labels: 🐣 Feat

#24 [OMCT-109] CommonIconButton 컴포넌트 구현
  src/components/common/IconButton/index.tsx
Labels: 🐣 Feat

#23 [OMCT-113] CommonText 컴포넌트 구현 및 util 함수 정의
  src/components/common/Text/index.tsx
  src/utils/conformText.ts
Labels: 🐣 Feat

#20 [OMCT-100] CommonAvatar 컴포넌트 구현
  src/components/common/Avatar/index.tsx
Labels: 🐣 Feat

#17 [OMCT-111] Header 컴포넌트 구현
  src/components/common/Header/index.tsx
Labels: 🐣 Feat

#26 [OMCT-122] CommonSelect 컴포넌트 구현
  src/components/common/Select/index.tsx
Labels: 🐣 Feat

#30 [OMCT-105] Profile 컴포넌트 구현
  src/components/common/Profile/index.tsx
Labels: 🐣 Feat

#21 [OMCT-114] CommonTextarea 컴포넌트 구현
  src/components/common/Textarea/index.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#25 [OMCT-104] CommonMenu 컴포넌트 구현
  src/components/common/Menu/index.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#27 [OMCT-102] CommonRadio 컴포넌트 제작
  src/components/common/Radio/RadioCard.tsx
  src/components/common/Radio/index.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#28 [OMCT-118] CommonTag 컴포넌트 구현
  src/components/common/Tag/index.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#32 [OMCT-119] Footer 컴포넌트 구현
  src/components/common/Footer/index.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#33 [OMCT-69] CommonToast 컴포넌트 구현
  src/components/common/Toast/index.tsx
  src/hooks/useCustomToast.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#34 [OMCT-108] CommonInput 컴포넌트 구현
  src/components/common/Input/index.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#35 [OMCT-112] CommonSkeleton 컴포넌트 구현
  src/components/common/Skeleton/index.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#36 [OMCT-125] router 구현
  src/App.tsx
  src/main.tsx
  src/routes/index.ts
  src/routes/router.tsx
Labels: 🐣 Feat

#29 [OMCT-117] CommonCard 컴포넌트 구현
  src/components/common/Card/index.tsx
Labels: 🐣 Feat

#31 [OMCT-106] CommonButton 컴포넌트 구현
  src/components/common/Button/index.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#37 [OMCT-142] 폴더 구조 재정의
  src/assets/vite.svg
  src/core/mocks/browser.js
  src/core/mocks/handler.ts
  src/core/mocks/index.ts
  src/core/routes/index.ts
  src/core/routes/router.tsx
  src/features/bucket/components/index.ts
  src/features/bucket/hooks/index.ts
  src/features/bucket/index.ts
  src/features/bucket/service/index.ts
  src/features/feed/components/index.ts
  src/features/feed/hooks/index.ts
  src/features/feed/index.ts
  src/features/feed/service/index.ts
  src/features/item/components/index.ts
  src/features/item/hooks/index.ts
  src/features/item/index.ts
  src/features/item/service/index.ts
  src/main.tsx
  src/shared/components/Avatar/index.tsx
  src/shared/components/Badge/index.tsx
  src/shared/components/Button/index.tsx
  src/shared/components/Card/index.tsx
  src/shared/components/Divider/index.tsx
  src/shared/components/Drawer/index.tsx
  src/shared/components/Footer/index.tsx
  src/shared/components/Header/index.tsx
  src/shared/components/Icon/index.tsx
  src/shared/components/IconButton/index.tsx
  src/shared/components/Image/index.tsx
  src/shared/components/Input/index.tsx
  src/shared/components/Menu/index.tsx
  src/shared/components/Profile/index.tsx
  src/shared/components/Radio/RadioCard.tsx
  src/shared/components/Radio/index.tsx
  src/shared/components/Select/index.tsx
  src/shared/components/Skeleton/index.tsx
  src/shared/components/Slider/index.tsx
  src/shared/components/Tabs/index.tsx
  src/shared/components/Tag/index.tsx
  src/shared/components/Text/index.tsx
  src/shared/components/Textarea/index.tsx
  src/shared/components/Toast/index.tsx
  src/shared/components/index.ts
  src/shared/constants/index.ts
  src/shared/hooks/index.ts
  src/shared/hooks/useCustomToast.tsx
  src/shared/types/index.ts
  src/shared/utils/conformText.ts
Labels: 🛠 Refactor

#38 [OMCT-153] CommonAvatar 컴포넌트 수정
  src/shared/components/Avatar/index.tsx
Labels: 🔨 Fix, 🛠 Refactor

#39 [OMCT-143] 경로 별칭 추가 및 반영
  src/core/routes/router.tsx
  src/shared/components/Avatar/index.tsx
  src/shared/components/Button/index.tsx
  src/shared/components/Card/index.tsx
  src/shared/components/Footer/index.tsx
  src/shared/components/Header/index.tsx
  src/shared/components/IconButton/index.tsx
  src/shared/components/Menu/index.tsx
  src/shared/components/Profile/index.tsx
  src/shared/components/Radio/RadioCard.tsx
  src/shared/components/Tag/index.tsx
  src/shared/components/Text/index.tsx
  src/shared/components/Toast/index.tsx
  src/shared/components/index.ts
  src/shared/hooks/useCustomToast.tsx
  tsconfig.json
Labels: 🏅 Chore, 🛠 Refactor

#40 [OMCT-79] Vote handler 작성 및 서비스워커 등록
  public/mockServiceWorker.js
  src/core/mocks/browser.ts
  src/core/mocks/handler/vote.ts
  src/core/mocks/response/vote.ts
Labels: 🐣 Feat

#41 [OMCT-155] CommonDivider 컴포넌트 수정
  src/shared/components/Divider/index.tsx
Labels: 🛠 Refactor

#44 [OMCT-163] 경로 별칭 오류 수정
  vite.config.ts
Labels: 🔨 Fix

#42 [OMCT-149] DateText 컴포넌트 구현
  src/shared/components/DateText/index.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#43 [OMCT-81] Feed handler 작성
  src/core/mocks/browser.ts
  src/core/mocks/handler/feed.ts
  src/core/mocks/response/feed.ts
Labels: 🐣 Feat

#45 [OMCT-144] import/order 설정
  .eslintrc.cjs
  package-lock.json
  package.json
Labels: 🏅 Chore

#46 [OMCT-159] CommonText 컴포넌트 수정
  src/shared/components/Text/index.tsx
Labels: 🔨 Fix

#47 [OMCT-164] App 레이아웃 설정
  src/App.tsx
Labels: 🎨 Design

#48 [NO-JIRA] 배럴 파일 수정 및 import order 반영
  src/shared/components/Card/index.tsx
  src/shared/components/Drawer/index.tsx
  src/shared/components/Header/index.tsx
  src/shared/components/Input/index.tsx
  src/shared/components/Radio/index.tsx
  src/shared/components/Select/index.tsx
  src/shared/components/Tag/index.tsx
  src/shared/components/Text/index.tsx
  src/shared/components/Textarea/index.tsx
  src/shared/components/index.ts
  src/shared/hooks/index.ts
  src/shared/utils/index.ts
Labels: 🛠 Refactor

#49 [OMCT-78] MSW Item handler 작성
  src/core/mocks/browser.ts
  src/core/mocks/handler/item.ts
  src/core/mocks/response/item.ts
Labels: 🐣 Feat

#51 [OMCT-154] CommonBadge 컴포넌트 수정
  src/shared/components/Badge/index.tsx
Labels: 🎨 Design, 🛠 Refactor

#50 [OMCT-165] font설정, 색상 변수 추가
  public/fonts/Cafe24Ohsquare-v2.0.woff2
  public/fonts/Cafe24OhsquareAir-v2.0.woff2
  src/main.css
  src/main.tsx
  src/shared/styles/Common.ts
  src/shared/styles/GlobalStyle.tsx
Labels: 🎨 Design, 수정사항 반영 완료

#54 [NO-JIRA] 폰트 파일 이동 및 msw 오류 해결
  src/assets/fonts/Cafe24Ohsquare-v2.0.woff2
  src/assets/fonts/Cafe24OhsquareAir-v2.0.woff2
  src/core/mocks/browser.js
  src/core/mocks/handler.ts
  src/main.css
Labels: 🔨 Fix

#53 [OMCT-161] CommonDividerImage 컴포넌트 구현
  src/shared/components/DividerImage/index.tsx
  src/shared/components/index.ts
Labels: 🐣 Feat

#55 [OMCT-174] Header 컴포넌트 수정, Image 타입 수정
  src/shared/components/Header/index.tsx
  src/shared/components/Image/index.tsx
Labels: 🛠 Refactor, 수정사항 반영 완료

#56 [OMCT-156] CommonDrawer 컴포넌트 수정
  src/shared/components/Drawer/index.tsx
Labels: 🎨 Design

#59 [OMCT-179] CommonImage 컴포넌트 작은 이미지 반응형 수정
  src/shared/components/Image/index.tsx
Labels: 🔨 Fix

#58 [OMCT-178] 투표상세페이지 ui 구현
  src/core/routes/router.tsx
  src/features/vote/components/VoteOptionItem/index.tsx
  src/features/vote/components/index.ts
  src/features/vote/hooks/index.ts
  src/features/vote/index.ts
  src/features/vote/service/index.ts
  src/pages/Vote/VoteDetail/index.tsx
  src/pages/Vote/VoteDetail/style.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#60 [OMCT-162] FeedItem 컴포넌트 구현
  src/features/feed/components/FeedItem/index.tsx
  src/features/feed/components/FeedItem/style.tsx
Labels: 🐣 Feat

#61 [OMCT-185] Common Radio, Button 컴포넌트 수정
  src/shared/components/Button/index.tsx
  src/shared/components/Radio/RadioCard.tsx
  src/shared/components/Radio/index.tsx
Labels: 🛠 Refactor

#64 [OMCT-181] 투표 생성페이지 ui 구현
  src/core/routes/router.tsx
  src/features/vote/components/VoteSelectItem/index.tsx
  src/features/vote/components/VoteSelectItem/style.ts
  src/pages/Vote/VoteCreate/index.tsx
  src/pages/Vote/VoteCreate/style.ts
Labels: 🎨 Design

#66 [OMCT-184] FeedCreate 페이지 구현, CommonTextarea 컴포넌트 수정, CommonButton 컴포넌트 수정, DividerImage 컴포넌트 수정
  src/core/routes/router.tsx
  src/features/feed/components/FeedSelectBucket/index.tsx
  src/features/feed/components/FeedSelectBucket/style.tsx
  src/features/feed/components/index.ts
  src/pages/Feed/FeedCreate/index.tsx
  src/pages/Feed/FeedCreate/style.tsx
  src/pages/index.ts
  src/shared/components/Button/index.tsx
  src/shared/components/DividerImage/index.tsx
  src/shared/components/Textarea/index.tsx
Labels: 🎨 Design, 🐣 Feat, 🔨 Fix

#63 [OMCT-186] footer컴포넌트/icon컴포넌트/iconbutton컴포넌트 수정
  src/shared/components/Footer/index.tsx
  src/shared/components/Icon/index.tsx
  src/shared/components/IconButton/index.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useSamePath.tsx
Labels: 🐣 Feat, 🔨 Fix, 수정사항 반영 완료

#65 [OMCT-187] QueryClientProvider 설정 및 Devtool 설정
  src/core/query/QueryClientProvider.tsx
  src/core/query/index.ts
  src/main.tsx
Labels: 🐣 Feat

#69 [OMCT-168] ItemList 페이지 구현/유틸함수 정의/msw item 수정
  src/core/mocks/handler/item.ts
  src/core/mocks/response/item.ts
  src/core/routes/router.tsx
  src/features/item/components/ItemList/index.tsx
  src/features/item/components/ItemList/style.tsx
  src/features/item/components/index.ts
  src/pages/Item/List/index.tsx
  src/pages/Item/List/style.tsx
  src/shared/utils/formatNumber.ts
  src/shared/utils/index.ts
Labels: 🐣 Feat

#71 [OMCT-188] 투표 페이지 ui 구현
  src/core/routes/router.tsx
  src/features/vote/components/VoteInProgress/index.tsx
  src/features/vote/components/VoteItem/index.tsx
  src/features/vote/components/Votes/index.tsx
  src/main.css
  src/pages/Vote/VoteHome/index.tsx
  src/shared/components/Card/index.tsx
  src/shared/components/DividerImage/index.tsx
  src/shared/components/Tabs/index.tsx
Labels: 🎨 Design

#73 [OMCT-183] FeedDetail 페이지 구현, CommoInput 컴포넌트 수정, CommonButton 컴포넌트 수정, Header 컴포넌트 수정
  src/core/routes/router.tsx
  src/features/feed/components/FeedComment/index.tsx
  src/features/feed/components/FeedItem/index.tsx
  src/features/feed/components/FeedItem/style.tsx
  src/features/feed/components/index.ts
  src/pages/Feed/FeedDetail/index.tsx
  src/pages/index.ts
  src/shared/components/Button/index.tsx
  src/shared/components/Header/index.tsx
  src/shared/components/Input/index.tsx
Labels: 🎨 Design, 🐣 Feat, 🔨 Fix

#74 [OMCT-169] Item 생성 페이지 ui 구현 / CommonInput type 수정
  src/core/routes/router.tsx
  src/pages/Item/Create/index.tsx
  src/pages/Item/Create/style.tsx
Labels: 🐣 Feat

#75 [OMCT-201] 기본 Axios 세팅
  .env.example
  .gitignore
  src/core/service/axios.ts
  src/shared/utils/index.ts
  src/shared/utils/storage.ts
Labels: 🐣 Feat, 🐹 init

#79 [NO-JIRA] MSW package 삭제/serviceworker 삭제/mock 폴더 삭제
  package.json
  public/mockServiceWorker.js
  src/core/mocks/browser.ts
  src/core/mocks/handler/feed.ts
  src/core/mocks/handler/item.ts
  src/core/mocks/handler/vote.ts
  src/core/mocks/index.ts
  src/core/mocks/response/feed.ts
  src/core/mocks/response/item.ts
  src/core/mocks/response/vote.ts
  src/features/item/components/ItemList/index.tsx
  src/main.tsx
  src/pages/Item/List/index.tsx
  src/shared/types/feed.ts
  src/shared/types/item.ts
  src/shared/types/vote.ts
Labels: 🔨 Fix

#77 [OMCT-182] Home, FeedHome 페이지 구현 및 router 경로 수정
  src/core/routes/router.tsx
  src/features/feed/components/FeedComment/index.tsx
  src/features/feed/components/FeedComment/style.tsx
  src/features/vote/components/VoteInProgress/index.tsx
  src/features/vote/components/VoteInProgress/style.tsx
  src/features/vote/components/VoteItem/index.tsx
  src/features/vote/components/VoteItem/style.tsx
  src/features/vote/components/Votes/index.tsx
  src/features/vote/components/Votes/style.tsx
  src/pages/Feed/FeedDetail/index.tsx
  src/pages/Feed/FeedDetail/style.tsx
  src/pages/Feed/FeedHome/index.tsx
  src/pages/Feed/FeedHome/style.tsx
  src/pages/Home/index.tsx
  src/pages/Home/style.tsx
  src/pages/Vote/VoteHome/index.tsx
  src/pages/Vote/VoteHome/style.tsx
  src/pages/index.ts
  src/shared/components/Tabs/index.tsx
  vercel.json
Labels: 🐣 Feat, 🛠 Refactor

#81 [N O-JIRA] token이 없을때 발생하는 상황에 대처하는 axios 설정/LocalStorage 수정
  src/core/service/axios.ts
  src/shared/utils/storage.ts
Labels: 🔨 Fix

#82 [OMCT-204] FeedBucketDetail 컴포넌트 구현
  src/core/routes/router.tsx
  src/features/feed/components/FeedBucketDetail/index.tsx
  src/features/feed/components/index.ts
  src/pages/Feed/FeedDetail/index.tsx
  src/shared/components/Button/index.tsx
  src/shared/components/Drawer/index.tsx
Labels: 🐣 Feat

#83 [OMCT-213] 버킷 생성페이지 ui 구현
  src/core/routes/router.tsx
  src/features/bucket/components/BucketSelectItem/index.tsx
  src/features/bucket/components/BucketSelectItem/style.ts
  src/pages/Bucket/BucketCreate/index.tsx
  src/pages/Bucket/BucketCreate/style.ts
Labels: 🎨 Design

#84 [OMCT-171] ItemReview 페이지 ui 구현/Slider 컴포넌트 속성 추가
  src/core/routes/router.tsx
  src/pages/Item/Review/index.tsx
  src/pages/Item/Review/style.tsx
  src/shared/components/Slider/index.tsx
Labels: 🐣 Feat

#86 [OMCT-218] MemberHome 페이지 구현
  src/core/routes/router.tsx
  src/pages/Member/MemberHome/index.tsx
  src/pages/Member/MemberHome/style.tsx
  src/pages/index.ts
  src/shared/components/Avatar/index.tsx
  src/shared/components/Button/index.tsx
  src/shared/components/Footer/index.tsx
Labels: 🐣 Feat, 🛠 Refactor

#87 [OMCT-223] Item Axios handler 작성/ storage 수정
  src/core/service/axios.ts
  src/features/item/service/handler.ts
  src/features/item/service/index.ts
  src/features/item/service/types.ts
  src/shared/types/item.ts
  src/shared/utils/storage.ts
Labels: 🐣 Feat, 🔨 Fix

#90 [OMCT-225] 피드 api 부분적 구현
  src/features/feed/service/handler.ts
  src/features/feed/service/index.ts
  src/features/feed/service/types.ts
  src/features/hobby/handler.ts
  src/features/hobby/index.ts
  src/features/hobby/types.ts
  src/pages/Feed/FeedDetail/index.tsx
  src/pages/Feed/FeedHome/index.tsx
  src/shared/types/feed.ts
  src/shared/types/hobby.ts
Labels: 🐣 Feat, 🛠 Refactor

#91 [NO-JIRA] husky pre-push 설정 추가
  .husky/pre-push
Labels: 🐣 Feat

#92 [OMCT-225] 피드 api handler 구현
  src/features/feed/index.ts
  src/features/feed/service/handler.ts
  src/features/feed/service/types.ts
  src/shared/types/index.ts
Labels: 🐣 Feat

#93 [OMCT-235] Axios handler 구현
  src/features/item/components/ItemComment/index.tsx
  src/features/item/service/handler.ts
  src/features/item/service/index.ts
  src/features/item/service/types.ts
  src/pages/Item/Detail/index.tsx
  src/pages/Item/List/index.tsx
  src/shared/types/feed.ts
  src/shared/types/index.ts
  src/shared/types/item.ts
  src/shared/types/member.ts
  src/shared/types/review.ts
Labels: 🐣 Feat

#94 [OMCT-242] review handler 작성
  src/features/review/service/handler.ts
  src/features/review/service/index.ts
  src/features/review/service/types.ts
Labels: 🐣 Feat

#95 [OMCT-202] 회원가입 기능 구현
  src/core/routes/router.tsx
  src/features/member/hooks/index.ts
  src/features/member/hooks/useCheckEmail.ts
  src/features/member/hooks/useCheckNickname.ts
  src/features/member/hooks/useSignup.ts
  src/features/member/service/handler.ts
  src/features/member/service/types.ts
  src/pages/Member/Login/index.tsx
  src/pages/Member/Login/style.ts
  src/pages/Member/Signup/index.tsx
  src/pages/Member/Signup/style.ts
  src/pages/index.ts
  src/shared/components/Button/index.tsx
  src/shared/components/Input/index.tsx
  src/shared/hooks/useValidateForm.tsx
Labels: 🐣 Feat

#96 [OMCT-239] 댓글 api handler 구현
  src/features/comment/components/index.ts
  src/features/comment/hooks/index.ts
  src/features/comment/service/handler.ts
  src/features/comment/service/index.ts
  src/features/comment/service/types.ts
  src/shared/types/comment.ts
Labels: 🐣 Feat

#100 [OMCT-237] 멤버 관련 api handler 구현
  src/features/member/service/handler.ts
  src/features/member/service/types.ts
  src/shared/types/member.ts
Labels: 🐣 Feat

#97 [OMCT-246] 투표 api handler구현
  src/features/vote/components/index.ts
  src/features/vote/service/handler.ts
  src/features/vote/service/index.ts
  src/features/vote/service/types.ts
  src/pages/Vote/VoteCreate/index.tsx
  src/pages/Vote/VoteHome/index.tsx
  src/shared/types/index.ts
  src/shared/types/vote.ts
Labels: 🐣 Feat

#102 [NO-JIRA] 취미 관련 queryOption 추가 및 hook 추가
  src/features/hobby/components/index.ts
  src/features/hobby/hooks/index.ts
  src/features/hobby/hooks/useHobby.ts
  src/features/hobby/service/handler.ts
  src/features/hobby/service/index.ts
  src/features/hobby/service/queryOption.ts
  src/features/hobby/service/types.ts
  src/pages/Feed/FeedHome/index.tsx
  src/shared/types/feed.ts
Labels: 🐣 Feat

#103 [NO-JIRA] useDrawer hook 구현
  src/pages/Bucket/BucketCreate/index.tsx
  src/pages/Feed/FeedCreate/index.tsx
  src/pages/Feed/FeedDetail/index.tsx
  src/pages/Vote/VoteCreate/index.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useDrawer.tsx
Labels: 🐣 Feat

#104 [OMCT-251] MemberEdit 페이지 UI 구현
  src/pages/Member/MemberEdit/index.tsx
  src/pages/Member/MemberEdit/style.tsx
  src/shared/components/Textarea/index.tsx
Labels: 🐣 Feat

#105 [OMCT-254] MemberPassword 페이지 UI 구현
  src/core/routes/router.tsx
  src/pages/Member/MemberPassword/index.tsx
  src/pages/Member/MemberPassword/style.tsx
  src/pages/index.ts
  src/shared/components/Icon/index.tsx
Labels: 🐣 Feat

#106 [OMCT-260] 버킷 api handler 구현
  src/features/bucket/service/handler.ts
  src/features/bucket/service/index.ts
  src/features/bucket/service/queryOption.ts
  src/features/bucket/service/types.ts
  src/shared/types/bucket.ts
  src/shared/types/index.ts
Labels: 🐣 Feat

#107 [OMCT-215] 피드 페이지 api 연결
  src/features/feed/components/FeedItem/index.tsx
  src/features/feed/components/FeedItem/style.tsx
  src/features/feed/hooks/index.ts
  src/features/feed/hooks/useFeedDetail.ts
  src/features/feed/hooks/useFeeds.ts
  src/features/feed/service/handler.ts
  src/features/feed/service/index.ts
  src/features/feed/service/queryOption.ts
  src/features/feed/service/types.ts
  src/pages/Feed/FeedDetail/index.tsx
  src/pages/Feed/FeedHome/index.tsx
  src/pages/Feed/FeedHome/style.tsx
  src/shared/types/feed.ts
  src/shared/types/member.ts
Labels: 🐣 Feat

#108 [OMCT-267] 댓글 api 연결
  src/core/routes/router.tsx
  src/features/comment/hooks/useComments.ts
  src/features/comment/service/index.ts
  src/features/comment/service/queryOption.ts
  src/features/comment/service/types.ts
  src/features/feed/components/FeedComment/index.tsx
  src/features/feed/components/FeedItem/index.tsx
  src/features/item/components/ItemComment/index.tsx
  src/pages/Feed/FeedDetail/index.tsx
  src/pages/Feed/FeedDetail/style.tsx
  src/pages/Feed/FeedHome/index.tsx
  src/pages/Home/index.tsx
  src/shared/components/Profile/index.tsx
Labels: 🐣 Feat

#110 [NO-JIRA] meta태그 추가
  index.html
Labels: 🐣 Feat

#113 [NO-JIRA] meta 태그 삭제
  index.html
Labels: 🔨 Fix

#109 [OMCT-268] 페이지 이동시 로그인 여부 확인하는 훅 추가
  src/App.tsx
  src/core/query/QueryClientProvider.tsx
  src/pages/Feed/FeedHome/index.tsx
  src/pages/Feed/FeedHome/style.tsx
  src/pages/Home/index.tsx
  src/shared/components/Drawer/index.tsx
  src/shared/components/Footer/index.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useAuthNavigate.ts
  src/shared/hooks/useUserInfo.ts
Labels: 🐣 Feat

#116 [OMCT-282] JWT 유효성 검사 api handler 구현
  src/features/member/service/handler.ts
Labels: 🐣 Feat

#118 [OMCT-283] 댓글 추가, 삭제 api 연결 및 구현
  src/features/comment/components/CommentItem/index.tsx
  src/features/comment/components/CommentItem/style.tsx
  src/features/comment/components/index.ts
  src/features/comment/hooks/index.ts
  src/features/comment/hooks/useAddComment.ts
  src/features/comment/hooks/useComments.ts
  src/features/comment/hooks/useDeleteComment.ts
  src/features/comment/service/handler.ts
  src/features/comment/service/types.ts
  src/features/feed/components/FeedBucketDetail/index.tsx
  src/features/feed/components/FeedItemsDetail/index.tsx
  src/features/feed/components/FeedItemsDetail/style.tsx
  src/features/feed/components/index.ts
  src/pages/Feed/FeedDetail/index.tsx
  src/pages/Feed/FeedDetail/style.tsx
  src/pages/Feed/FeedHome/style.tsx
Labels: 🐣 Feat, 🛠 Refactor

#117 [OMCT-255] 투표 페이지 구현
  src/features/vote/components/VoteInProgress/index.tsx
  src/features/vote/components/VoteInProgress/style.tsx
  src/features/vote/components/VoteItem/index.tsx
  src/features/vote/components/VoteItem/style.tsx
  src/features/vote/components/Votes/index.tsx
  src/features/vote/components/Votes/style.tsx
  src/features/vote/service/handler.ts
  src/features/vote/service/index.ts
  src/features/vote/service/queryOption.ts
  src/features/vote/service/types.ts
  src/pages/Vote/VoteHome/index.tsx
  src/shared/components/Select/index.tsx
  src/shared/types/vote.ts
Labels: 🐣 Feat, 수정사항 반영 완료

#119 [OMCT-180] 투표 상세페이지 get api 연동
  src/features/vote/components/VoteItem/index.tsx
  src/features/vote/components/VoteOptionItem/index.tsx
  src/features/vote/components/VoteOptionItem/style.ts
  src/features/vote/hooks/index.ts
  src/features/vote/hooks/useDeleteVote.ts
  src/features/vote/hooks/useParticipationVote.ts
  src/features/vote/service/queryOption.ts
  src/pages/Vote/VoteDetail/index.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#115 [OMCT-227] 아이템 생성 api 연결
  src/core/service/axios.ts
  src/features/item/hooks/index.ts
  src/features/item/hooks/usePostItem.ts
  src/features/item/index.ts
  src/features/item/service/handler.ts
  src/features/item/service/index.ts
  src/features/item/service/queryOption.ts
  src/features/item/service/types.ts
  src/pages/Item/Create/index.tsx
  src/pages/Item/Create/style.tsx
  src/pages/Item/List/index.tsx
  src/shared/components/Radio/index.tsx
  src/shared/components/Radio/style.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#120 [OMCT-285] 피드 상세 페이지 수정 및 좋아요 기능 추가
  src/features/feed/components/FeedItem/index.tsx
  src/features/feed/components/FeedItem/style.tsx
  src/features/feed/components/FeedItemsDetail/index.tsx
  src/features/feed/hooks/index.ts
  src/features/feed/hooks/useFeedDetail.ts
  src/features/feed/hooks/useFeedLike.ts
  src/features/feed/hooks/useFeedUnLike.ts
  src/features/feed/hooks/useFeeds.ts
  src/features/feed/service/queryOption.ts
  src/features/feed/service/types.ts
  src/pages/Feed/FeedDetail/index.tsx
  src/pages/Feed/FeedHome/index.tsx
  src/pages/Member/MemberHome/index.tsx
  src/shared/components/Avatar/index.tsx
  src/shared/components/Button/index.tsx
  src/shared/components/Input/index.tsx
  src/shared/components/Profile/index.tsx
  src/shared/utils/ellipsisName.ts
  src/shared/utils/index.ts
Labels: 🐣 Feat, 🛠 Refactor

#121 [OMCT-258] 회원가입페이지 오타 수정, 예외 처리 강화
  src/pages/Member/Signup/index.tsx
Labels: 🛠 Refactor, 🔥 우선순위 높음

#122 [OMCT-287] 멤버 페이지의 로그아웃, 탈퇴 기능 구현
  src/features/member/hooks/index.ts
  src/features/member/hooks/useLeave.ts
  src/features/member/hooks/useLogout.ts
  src/features/member/service/index.ts
  src/features/member/service/queryOption.ts
  src/pages/Member/MemberHome/index.tsx
  src/pages/Member/MemberHome/style.tsx
  src/shared/constants/index.ts
  src/shared/constants/path.ts
  src/shared/constants/storage.ts
  src/shared/types/member.ts
  src/shared/utils/storage.ts
Labels: 🐣 Feat

#125 [OMCT-229] 아이템 detail 페이지 api 연결
  src/features/item/hooks/index.ts
  src/features/item/hooks/useTakeItem.ts
  src/features/item/service/handler.ts
  src/features/item/service/queryOption.ts
  src/features/review/service/index.ts
  src/features/review/service/queryOption.ts
  src/features/review/service/types.ts
  src/pages/Item/Detail/index.tsx
  src/pages/Item/Detail/style.tsx
  src/shared/components/Button/index.tsx
Labels: 🐣 Feat

#127 [OMCT-290] 피드 페이지 select 추가
  src/features/feed/service/queryOption.ts
  src/features/feed/service/types.ts
  src/pages/Feed/FeedHome/index.tsx
  src/pages/Feed/FeedHome/style.tsx
  src/pages/Home/index.tsx
  src/shared/components/Select/index.tsx
Labels: 🐣 Feat

#128 [OMCT-292] 피드 작성자만 댓글 채택하기 버튼 보이게 수정
  src/features/comment/components/CommentItem/index.tsx
  src/pages/Feed/FeedDetail/index.tsx
Labels: 🐣 Feat

#126 [OMCT-230] 리뷰 등록 api 연결
  src/features/review/hooks/index.ts
  src/features/review/hooks/usePostReview.ts
  src/features/review/service/handler.ts
  src/features/review/service/types.ts
  src/pages/Item/Detail/index.tsx
  src/pages/Item/Review/index.tsx
  src/shared/types/review.ts
Labels: 🐣 Feat

#129 [OMCT-296] 나의 아이템 목록 조회 api handler 작성
  src/features/item/service/handler.ts
  src/features/item/service/queryOption.ts
  src/features/item/service/types.ts
  src/shared/types/item.ts
Labels: 🐣 Feat, 수정사항 반영 완료, 🔥 우선순위 높음

#132 [OMCT-295] 피드 생성 기능 구현
  src/features/bucket/service/queryOption.ts
  src/features/bucket/service/types.ts
  src/features/comment/components/CommentItem/index.tsx
  src/features/feed/components/FeedSelectBucket/index.tsx
  src/features/feed/hooks/index.ts
  src/features/feed/hooks/useCreateFeed.ts
  src/pages/Feed/FeedCreate/index.tsx
  src/pages/Feed/FeedCreate/style.tsx
  src/pages/Feed/FeedDetail/index.tsx
Labels: 🐣 Feat

#133 [OMCT-301] 인벤토리 목록 ui 구현
  src/core/routes/router.tsx
  src/pages/Inventory/InventoryCreate/index.tsx
  src/pages/Inventory/InventoryCreate/style.ts
  src/pages/Inventory/InventoryDetail/index.tsx
  src/pages/Inventory/InventoryDetail/style.ts
  src/pages/Inventory/InventoryHome/index.tsx
  src/pages/Inventory/InventoryHome/style.ts
  src/pages/index.ts
Labels: 🎨 Design, 🐣 Feat

#134 [OMCT-293] 버킷 생성 기능 추가
  src/features/bucket/components/BucketSelectItem/index.tsx
  src/features/bucket/components/BucketSelectItem/style.ts
  src/features/bucket/components/index.ts
  src/features/bucket/hooks/index.ts
  src/features/bucket/hooks/useCreateBucket.ts
  src/features/bucket/service/handler.ts
  src/features/bucket/service/types.ts
  src/pages/Bucket/BucketCreate/index.tsx
  src/pages/Bucket/BucketCreate/style.ts
  src/shared/types/bucket.ts
Labels: 🐣 Feat

#135 [NO JIRA] 아이템 담기 시 동작 수정/아이템 디테일 페이지 수정
  src/features/item/components/index.ts
  src/features/item/hooks/useTakeItem.ts
  src/pages/Item/Detail/index.tsx
  src/pages/Item/Detail/style.tsx
Labels: 🔨 Fix

#138 [OMCT-302]인벤토리 상세페이지, 인벤토리 생성페이지 ui 구현
  src/features/inventroy/components/InventorySelectItem/index.tsx
  src/features/inventroy/components/InventorySelectItem/style.ts
  src/pages/Inventory/InventoryCreate/index.tsx
  src/pages/Inventory/InventoryCreate/style.ts
  src/pages/Inventory/InventoryDetail/index.tsx
  src/pages/Inventory/InventoryDetail/style.ts
Labels: 🎨 Design, 🐣 Feat

#141 [OMCT-291] 리뷰 수정 api 연결
  src/core/routes/router.tsx
  src/features/item/components/ItemComment/index.tsx
  src/features/review/hooks/index.ts
  src/features/review/hooks/useEditReview.ts
  src/features/review/hooks/usePostReview.ts
  src/features/review/service/handler.ts
  src/features/review/service/queryOption.ts
  src/features/review/service/types.ts
  src/pages/Item/Detail/index.tsx
  src/pages/Item/ReviewEdit/index.tsx
  src/pages/Item/ReviewEdit/style.tsx
  src/pages/index.ts
  src/shared/components/Slider/index.tsx
Labels: 🐣 Feat

#144 [OMCT-305] 인벤토리 handler api 구현
  src/features/inventroy/service/handler.ts
  src/features/inventroy/service/index.ts
  src/features/inventroy/service/types.ts
  src/shared/types/inventory.ts
Labels: 🐣 Feat

#145 [OMCT-307] 멤버 페이지 수정
  src/features/feed/components/FeedItem/index.tsx
  src/pages/Feed/FeedDetail/index.tsx
  src/pages/Member/MemberHome/index.tsx
  src/pages/Member/MemberHome/style.tsx
  src/shared/components/DividerImage/index.tsx
  src/shared/types/feed.ts
Labels: 🎨 Design, 🐣 Feat

#142 [OMCT-396] 리뷰 삭제 api 연결
  src/features/item/components/ItemComment/index.tsx
  src/features/item/hooks/usePostItem.ts
  src/features/review/hooks/index.ts
  src/features/review/hooks/useDeleteReview.ts
  src/features/review/hooks/useEditReview.ts
  src/pages/Item/Detail/index.tsx
Labels: 🐣 Feat

#143 [OMCT-308] 아이템 리스트 api 연결
  src/features/item/components/ItemList/index.tsx
  src/pages/Item/Detail/index.tsx
  src/pages/Item/List/index.tsx
Labels: 🐣 Feat

#146 [OMCT-314] 피드 삭제 기능 추가
  src/features/feed/components/FeedItem/index.tsx
  src/features/feed/hooks/index.ts
  src/features/feed/hooks/useDeleteFeed.ts
  src/pages/Bucket/BucketCreate/index.tsx
  src/pages/Feed/FeedDetail/index.tsx
Labels: 🐣 Feat

#149 [OMCT-316] 인벤토리 생성 api 구현
  src/features/inventory/components/InventorySelectItem/index.tsx
  src/features/inventory/components/InventorySelectItem/style.ts
  src/features/inventory/hook/index.ts
  src/features/inventory/hook/useCreateInventory.tsx
  src/features/inventory/service/handler.ts
  src/features/inventory/service/index.ts
  src/features/inventory/service/queryOption.ts
  src/features/inventory/service/types.ts
  src/features/inventroy/components/InventorySelectItem/index.tsx
  src/features/inventroy/components/InventorySelectItem/style.ts
  src/features/inventroy/service/index.ts
  src/pages/Inventory/InventoryCreate/index.tsx
  src/pages/Inventory/InventoryCreate/style.ts
  src/pages/Inventory/InventoryHome/index.tsx
  src/pages/Inventory/InventoryHome/style.ts
  src/shared/types/inventory.ts
Labels: 🐣 Feat, 수정사항 반영 완료

#150 [OMCT-319] 검색창 페이지 구현
  src/core/routes/router.tsx
  src/features/search/components/index.ts
  src/features/search/components/searchForm/index.tsx
  src/features/search/components/searchForm/style.tsx
  src/features/search/hooks/index.ts
  src/features/search/hooks/useSearchedKeywordStorage.ts
  src/pages/Search/SearchHome/index.tsx
  src/pages/Search/SearchHome/style.tsx
  src/pages/Search/SearchMain/index.tsx
  src/pages/Search/SearchMain/style.tsx
  src/pages/index.ts
  src/shared/constants/storage.ts
  src/shared/hooks/useAuthCheck.ts
Labels: 🐣 Feat

#151 [OMCT-317] 프로필 수정 기능 연결
  src/features/member/components/MemberEditForm/index.tsx
  src/features/member/components/MemberEditForm/style.ts
  src/features/member/components/index.ts
  src/features/member/hooks/index.ts
  src/features/member/hooks/useUpdateMemberInfo.ts
  src/pages/Member/MemberEdit/index.tsx
  src/pages/Member/MemberEdit/style.tsx
Labels: 🐣 Feat, 🛠 Refactor

#152 [OMCT-323] 검색 api handler 작성
  src/features/item/service/handler.ts
  src/features/item/service/queryOption.ts
  src/features/item/service/types.ts
  src/features/search/service/handler.ts
  src/features/search/service/index.ts
  src/features/search/service/queryOption.ts
  src/features/search/service/types.ts
Labels: 🐣 Feat

#154 [OMCT-330] 피드 수정 페이지 UI 구현 및 HobbyRadio 컴포넌트 추가
  src/core/routes/router.tsx
  src/features/hobby/components/HobbyRadio/index.tsx
  src/features/hobby/components/HobbyRadio/style.ts
  src/features/hobby/components/index.ts
  src/pages/Feed/FeedCreate/index.tsx
  src/pages/Feed/FeedDetail/index.tsx
  src/pages/Feed/FeedUpdate/index.tsx
  src/pages/Feed/FeedUpdate/style.ts
  src/pages/index.ts
  src/shared/components/Radio/index.tsx
Labels: 🐣 Feat, 🛠 Refactor

#153 [OMCT-326] 비밀번호 변경 기능 연결
  src/features/member/components/MemberPasswordForm/index.tsx
  src/features/member/components/MemberPasswordForm/style.ts
  src/features/member/components/index.ts
  src/features/member/hooks/index.ts
  src/features/member/hooks/useUpdatePassword.ts
  src/features/member/service/queryOption.ts
  src/pages/Member/MemberPassword/index.tsx
  src/pages/Member/MemberPassword/style.tsx
Labels: 🐣 Feat

#155 [OMCT-315] 인벤토리 상세 조회, 삭제, 수정 api 구현
  src/features/inventory/components/InventorySelectItem/index.tsx
  src/features/inventory/hook/index.ts
  src/features/inventory/hook/useDeleteInventory.tsx
  src/features/inventory/hook/useUpdateInventory.tsx
  src/features/inventory/service/handler.ts
  src/features/inventory/service/queryOption.ts
  src/pages/Inventory/InventoryCreate/index.tsx
  src/pages/Inventory/InventoryDetail/index.tsx
  src/pages/Inventory/InventoryHome/index.tsx
  src/pages/Inventory/InventoryHome/style.ts
Labels: 🐣 Feat

#156 [OMCT-337] 피드 수정 api 연결
  src/features/feed/hooks/index.ts
  src/features/feed/hooks/useUpdateFeed.ts
  src/features/feed/service/handler.ts
  src/pages/Feed/FeedUpdate/index.tsx
Labels: 🐣 Feat

#161 [OMCT-341] 버킷 목록, 상세 페이지 UI 구현
  src/core/routes/router.tsx
  src/pages/Bucket/BucketDetail/index.tsx
  src/pages/Bucket/BucketDetail/style.ts
  src/pages/Bucket/BucketHome/index.tsx
  src/pages/Bucket/BucketHome/style.ts
  src/pages/index.ts
  src/shared/components/Tabs/index.tsx
Labels: 🐣 Feat

#162 [OMCT-343] 버킷 관련 api 연결 및 수정 페이지 임시로 추가
  src/core/routes/router.tsx
  src/features/bucket/components/BucketUpdateItem/index.tsx
  src/features/bucket/components/BucketUpdateItem/style.ts
  src/features/bucket/components/index.ts
  src/features/bucket/hooks/index.ts
  src/features/bucket/hooks/useDeleteBucket.ts
  src/features/bucket/hooks/useUpdateBucket.ts
  src/features/bucket/service/handler.ts
  src/features/bucket/service/queryOption.ts
  src/features/bucket/service/types.ts
  src/pages/Bucket/BucketDetail/index.tsx
  src/pages/Bucket/BucketDetail/style.ts
  src/pages/Bucket/BucketHome/index.tsx
  src/pages/Bucket/BucketHome/style.ts
  src/pages/Bucket/BucketUpdate/index.tsx
  src/pages/Bucket/BucketUpdate/style.ts
  src/pages/Feed/FeedUpdate/index.tsx
  src/pages/index.ts
  src/shared/components/Header/index.tsx
  src/shared/types/bucket.ts
Labels: 🎨 Design, 🐣 Feat

#160 [OMCT-321] 검색 api 연결
  src/features/search/components/index.ts
  src/features/search/components/latelySearch/index.tsx
  src/features/search/components/latelySearch/style.tsx
  src/features/search/components/searchForm/index.tsx
  src/features/search/components/searchList/index.tsx
  src/features/search/components/searchList/style.tsx
  src/features/search/service/handler.ts
  src/features/search/service/index.ts
  src/features/search/service/queryOption.ts
  src/features/search/service/types.ts
  src/pages/Search/SearchHome/index.tsx
  src/pages/Search/SearchMain/index.tsx
  src/pages/Search/SearchMain/style.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#165 [OMCT-354] 버킷 수정 기능 구현
  src/features/bucket/components/BucketSelectedItems/index.tsx
  src/features/bucket/components/BucketSelectedItems/style.ts
  src/features/bucket/components/index.ts
  src/features/bucket/hooks/useCreateBucket.ts
  src/features/bucket/hooks/useUpdateBucket.ts
  src/pages/Bucket/BucketCreate/index.tsx
  src/pages/Bucket/BucketUpdate/index.tsx
  src/shared/components/Radio/RadioCard.tsx
Labels: 🐣 Feat

#166 [OMCT-297] 인벤토리 페이지 리팩토링
  src/features/hobby/components/HobbySelector/index.tsx
  src/features/hobby/components/HobbySelector/style.ts
  src/features/inventory/components/ UpdateInventoryDetail/index.tsx
  src/features/inventory/components/DeleteInventoryDetail/index.tsx
  src/features/inventory/components/InventorySelectItem/index.tsx
  src/features/inventory/service/types.ts
  src/pages/Inventory/InventoryCreate/index.tsx
  src/pages/Inventory/InventoryDetail/index.tsx
  src/pages/Inventory/InventoryHome/index.tsx
Labels: 🛠 Refactor

#167 [OMCT-342] 검색 결과 페이지 ui 구현
  src/core/routes/router.tsx
  src/features/search/components/index.ts
  src/features/search/components/searchItemList/index.tsx
  src/features/search/components/searchItemList/style.tsx
  src/features/search/components/searchVoteList/index.tsx
  src/features/search/components/searchVoteList/style.tsx
  src/pages/Search/SearchHome/style.tsx
  src/pages/Search/SearchResult/index.tsx
  src/pages/Search/SearchResult/style.tsx
  src/pages/index.ts
  src/shared/components/Tabs/index.tsx
Labels: 🐣 Feat

#168 [OMCT-309] 아이템 삭제 api 연결
  src/features/item/hooks/index.ts
  src/features/item/hooks/useDeleteItem.ts
  src/features/item/service/handler.ts
  src/features/item/service/types.ts
  src/pages/Item/List/index.tsx
Labels: 🐣 Feat

#169 [OMCT-321] 검색 결과 api 연결
  src/features/search/components/searchForm/index.tsx
  src/features/search/components/searchItemList/index.tsx
  src/features/search/components/searchItemList/style.tsx
  src/features/search/components/searchList/index.tsx
  src/features/search/components/searchVoteList/index.tsx
  src/features/search/components/searchVoteList/style.tsx
  src/features/search/service/queryOption.ts
  src/features/search/service/types.ts
  src/pages/Search/SearchHome/index.tsx
  src/pages/Search/SearchResult/index.tsx
Labels: 🐣 Feat

#173 [OMCT-374] 리뷰 ui 수정
  src/features/item/components/ItemComment/index.tsx
  src/pages/Item/Detail/index.tsx
Labels: 🎨 Design

#172 [OMCT-370] 검색 디바운스 적용
  src/features/search/components/searchForm/index.tsx
  src/features/search/hooks/index.ts
  src/features/search/hooks/useDebounce.ts
Labels: 🐣 Feat, 🛠 Refactor

#174 [NO-JIRA] useIntersectionObserver 훅 추가
  src/shared/hooks/index.ts
  src/shared/hooks/useIntersectionObserver.ts
Labels: 🐣 Feat

#171 [OMCT-368] 투표 페이지 무한스크롤 구현 + qa수정
  src/features/vote/components/VoteInProgress/index.tsx
  src/features/vote/components/VoteItem/index.tsx
  src/features/vote/components/VoteItem/style.tsx
  src/features/vote/components/VoteList/index.tsx
  src/features/vote/components/VoteOptionItem/index.tsx
  src/features/vote/components/VoteSelectItem/index.tsx
  src/features/vote/components/VoteSelectItem/style.ts
  src/features/vote/components/Votes/index.tsx
  src/features/vote/service/queryOption.ts
  src/pages/Vote/VoteCreate/index.tsx
  src/pages/Vote/VoteDetail/index.tsx
  src/pages/Vote/VoteHome/index.tsx
  src/shared/components/Badge/index.tsx
  src/shared/components/Card/index.tsx
Labels: 🛠 Refactor

#175 [OMCT-373] 피드 목록과 댓글에 무한 스크롤 적용
  src/features/comment/components/CommentItem/style.tsx
  src/features/comment/components/CommentList/index.tsx
  src/features/comment/components/CommentList/style.ts
  src/features/comment/components/index.ts
  src/features/comment/service/queryOption.ts
  src/features/comment/service/types.ts
  src/features/feed/components/FeedHomeList/index.tsx
  src/features/feed/components/FeedHomeList/style.ts
  src/features/feed/components/FeedList/index.tsx
  src/features/feed/components/FeedMemberContents/index.tsx
  src/features/feed/components/FeedMemberContents/style.ts
  src/features/feed/components/FeedMemberList/index.tsx
  src/features/feed/components/FeedMemberList/style.ts
  src/features/feed/components/index.ts
  src/features/feed/service/handler.ts
  src/features/feed/service/queryOption.ts
  src/features/feed/service/types.ts
  src/pages/Feed/FeedDetail/index.tsx
  src/pages/Feed/FeedHome/index.tsx
  src/pages/Feed/FeedMember/index.tsx
  src/pages/Member/MemberHome/index.tsx
Labels: 🐣 Feat

#176 [OMCT-381] QA 반영
  src/features/bucket/components/BucketSelectItem/index.tsx
  src/features/bucket/components/BucketSelectItem/style.ts
  src/features/bucket/components/BucketUpdateItem/index.tsx
  src/features/bucket/components/BucketUpdateItem/style.ts
  src/features/bucket/hooks/useCreateBucket.ts
  src/features/comment/components/CommentItem/index.tsx
  src/features/feed/components/FeedSelectBucket/index.tsx
  src/features/feed/components/FeedSelectBucket/style.tsx
  src/features/hobby/components/HobbyRadio/index.tsx
  src/features/hobby/components/index.ts
  src/features/member/components/MemberEditForm/index.tsx
  src/pages/Bucket/BucketCreate/index.tsx
  src/pages/Bucket/BucketCreate/style.ts
  src/pages/Bucket/BucketUpdate/index.tsx
  src/pages/Feed/FeedCreate/index.tsx
  src/pages/Feed/FeedDetail/index.tsx
  src/pages/Member/MemberHome/index.tsx
  src/pages/Member/MemberHome/style.tsx
  src/shared/components/Button/index.tsx
  src/shared/hooks/useValidateForm.tsx
Labels: 🐣 Feat, 수정사항 반영 완료

#177 [OMCT-382] 검색 QA 피드백 구현
  src/features/feed/components/FeedItemsDetail/index.tsx
  src/features/search/components/latelySearch/index.tsx
  src/features/search/components/searchForm/index.tsx
  src/features/search/components/searchItemList/style.tsx
  src/features/search/components/searchList/index.tsx
  src/features/search/components/searchVoteList/style.tsx
  src/features/search/service/index.ts
  src/features/search/service/searchLocalStorage.ts
  src/shared/utils/ellipsisName.ts
Labels: 🐣 Feat, 🔨 Fix, 수정사항 반영 완료

#180 [OMCT-387] QA 1차 진행
  src/features/inventory/components/InventorySelectItem/index.tsx
  src/features/vote/components/VoteInProgress/index.tsx
  src/features/vote/components/VoteItem/index.tsx
  src/features/vote/components/VoteItem/style.tsx
  src/features/vote/components/VoteOptionItem/index.tsx
  src/pages/Inventory/InventoryCreate/index.tsx
  src/pages/Inventory/InventoryDetail/index.tsx
  src/pages/Inventory/InventoryHome/index.tsx
  src/pages/Member/Login/index.tsx
  src/pages/Vote/VoteCreate/index.tsx
  src/pages/Vote/VoteDetail/index.tsx
Labels: 🛠 Refactor

#182 [OMCT-390] 회원가입페이지 컴포넌트 분리, CommonText 수정
  src/features/member/components/MemberEmailForm/index.tsx
  src/features/member/components/MemberEmailForm/style.ts
  src/features/member/components/MemberNicknameForm/index.tsx
  src/features/member/components/MemberNicknameForm/style.ts
  src/features/member/components/MemberPassword/index.tsx
  src/pages/Member/Signup/index.tsx
  src/shared/components/Text/index.tsx
  src/shared/styles/GlobalStyle.tsx
Labels: 🛠 Refactor

#184 [OMCT-388] 버킷 관련 무한 스크롤 구현, QA 반영, 새로운 api 명세 반영
  src/features/bucket/components/BucketList/index.tsx
  src/features/bucket/components/BucketList/style.ts
  src/features/bucket/components/BucketSelectItem/index.tsx
  src/features/bucket/components/BucketUpdateItem/index.tsx
  src/features/bucket/components/index.ts
  src/features/bucket/service/queryOption.ts
  src/features/bucket/service/types.ts
  src/features/comment/components/CommentItem/index.tsx
  src/features/comment/hooks/useAddComment.ts
  src/features/comment/service/types.ts
  src/features/feed/components/FeedItem/index.tsx
  src/features/feed/components/FeedItem/style.tsx
  src/features/feed/components/FeedItemsDetail/index.tsx
  src/features/feed/components/FeedItemsDetail/style.tsx
  src/features/feed/components/FeedMemberList/index.tsx
  src/features/feed/components/FeedSelectBucket/index.tsx
  src/features/feed/components/FeedSelectBucket/style.tsx
  src/features/feed/service/queryOption.ts
  src/features/item/service/types.ts
  src/features/search/components/searchItemList/index.tsx
  src/pages/Bucket/BucketCreate/index.tsx
  src/pages/Bucket/BucketDetail/index.tsx
  src/pages/Bucket/BucketHome/index.tsx
  src/pages/Bucket/BucketHome/style.ts
  src/pages/Bucket/BucketUpdate/index.tsx
  src/pages/Feed/FeedCreate/index.tsx
  src/pages/Feed/FeedDetail/index.tsx
  src/pages/Feed/FeedHome/index.tsx
  src/shared/components/Button/index.tsx
  src/shared/components/DividerImage/index.tsx
  src/shared/hooks/useValidateForm.tsx
Labels: 🐣 Feat, 🔨 Fix, 🛠 Refactor

#185 [NO-JIRA] 버킷 오류 및 size 수정
  src/features/item/service/handler.ts
  src/shared/components/DividerImage/index.tsx
Labels: 🔨 Fix

#186 [OMCT-372] 아이템 리스트 무한스크롤 구현
  src/features/item/service/queryOption.ts
  src/features/item/service/types.ts
  src/pages/Item/List/index.tsx
Labels: 🐣 Feat, 🛠 Refactor

#187 [NO-JIRA] 나의 버킷 디자인 수정
  src/features/bucket/components/BucketList/style.ts
Labels: 🔨 Fix

#188 [OMCT-376] 검색 페이지 무한스크롤 구현
  src/features/search/components/searchForm/index.tsx
  src/features/search/components/searchItemList/index.tsx
  src/features/search/components/searchList/index.tsx
  src/features/search/components/searchVoteList/index.tsx
  src/features/search/service/queryOption.ts
  src/pages/Search/SearchHome/style.tsx
  src/pages/Search/SearchResult/index.tsx
  src/pages/Search/SearchResult/style.tsx
Labels: 🐣 Feat, 🛠 Refactor
